import React from "react";
import {AbsoluteFill, interpolate, spring, useCurrentFrame} from "remotion";
import {z} from "zod";

export const lessonVideoSchema = z.object({title: z.string(), hook: z.string(), keyPoints: z.array(z.string()).min(1).max(3), takeaway: z.string(), sourceName: z.string().default("Учебный материал")});
type Lesson = z.infer<typeof lessonVideoSchema>;
const palette = ["#5334d1", "#056f8b", "#0d806b", "#d55b24", "#7637a7"];
const Page: React.FC<{children: React.ReactNode; index: number; total: number}> = ({children, index, total}) => { const frame = useCurrentFrame(); const accent = palette[index % palette.length]; const enter = spring({frame, fps: 30, config: {damping: 18, stiffness: 130}}); return <AbsoluteFill style={{background: `radial-gradient(circle at 90% 8%, ${accent} 0%, #151629 38%, #0c0c16 100%)`, color: "white", fontFamily: "Arial, sans-serif", overflow: "hidden"}}><div style={{position: "absolute", top: 70, left: 70, right: 70, display: "flex", gap: 8}}>{Array.from({length: total}, (_, i) => <div key={i} style={{height: 8, flex: 1, borderRadius: 8, background: i <= index ? "#ffffff" : "rgba(255,255,255,.25)"}} />)}</div><div style={{position: "absolute", inset: 0, display: "flex", flexDirection: "column", justifyContent: "center", padding: "120px 82px", opacity: enter, transform: `translateY(${(1 - enter) * 60}px)`}}>{children}</div><div style={{position: "absolute", bottom: 68, left: 82, right: 82, display: "flex", justifyContent: "space-between", color: "rgba(255,255,255,.65)", fontSize: 25}}><span>ETAP · учимся коротко</span><span>{String(index + 1).padStart(2, "0")}/{String(total).padStart(2, "0")}</span></div></AbsoluteFill>; };
const Text: React.FC<{children: React.ReactNode}> = ({children}) => <div style={{fontSize: 68, lineHeight: 1.16, fontWeight: 750, letterSpacing: -1.5}}>{children}</div>;
export const LessonVideo: React.FC<Lesson> = ({title, hook, keyPoints, takeaway, sourceName}) => { const frame = useCurrentFrame(); const scenes = [<><div style={{fontSize: 29, letterSpacing: 3, textTransform: "uppercase", opacity: .7, marginBottom: 35}}>Разбираем за минуту</div><Text>{title}</Text><div style={{marginTop: 55, fontSize: 36, lineHeight: 1.35, opacity: .84}}>{hook}</div></>, ...keyPoints.map((point, index) => <><div style={{fontSize: 32, opacity: .7, marginBottom: 30}}>Ключевая идея {index + 1}</div><div style={{fontSize: 170, fontWeight: 800, color: "#f5d264", marginBottom: 28}}>0{index + 1}</div><Text>{point}</Text></>), <><div style={{fontSize: 32, opacity: .7, marginBottom: 30}}>Запомните</div><Text>{takeaway}</Text><div style={{marginTop: 65, padding: "26px 30px", borderLeft: "6px solid #f5d264", background: "rgba(255,255,255,.09)", fontSize: 30}}>{sourceName}</div></>]; const sceneDuration = 1800 / scenes.length; const active = Math.min(scenes.length - 1, Math.floor(frame / sceneDuration)); const localFrame = frame - active * sceneDuration; const fade = interpolate(localFrame, [0, 10, sceneDuration - 14, sceneDuration], [0, 1, 1, 0], {extrapolateLeft: "clamp", extrapolateRight: "clamp"}); return <div style={{opacity: fade}}><Page index={active} total={scenes.length}>{scenes[active]}</Page></div>; };
